name = "bingogenerator"
type = "javascript"

[build]
command = "yarn build"
[build.upload]
format = "service-worker"
directory = "build"

[env.production]
account_id = "your_account_id"
workers_dev = true
route = "your_custom_route"
zone_id = "your_zone_id"
